In [74]:
import numpy as np

# array
print(np.zeros(5, dtype='float'))
print(np.ones(6, dtype='int'))
print(np.eye(3))
print(np.ones((2, 3)))


[0. 0. 0. 0. 0.]
[1 1 1 1 1 1]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [75]:
print(np.full((3, 5), 1.2))

[[1.2 1.2 1.2 1.2 1.2]
 [1.2 1.2 1.2 1.2 1.2]
 [1.2 1.2 1.2 1.2 1.2]]


In [76]:
print(np.arange(2, 9, 3))
print(np.linspace(2, 10, 5))


[2 5 8]
[ 2.  4.  6.  8. 10.]


In [77]:
ar = np.array([1, 2, 3, 4, 5])
print(ar)
print(ar[3])
print(ar[:3])

[1 2 3 4 5]
4
[1 2 3]


In [78]:
ar2d = np.array([[1, 2, 3], [4, 5, 6]])
print(ar2d[0, 1])

2


In [79]:
print(np.concatenate([ar2d, ar2d]))
ar3 = np.array([6, 7, 8])
print(np.vstack([ar2d, ar3]))
ar4 = np.array([[4], [5]])
print(np.hstack([ar2d, ar4]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [6 7 8]]
[[1 2 3 4]
 [4 5 6 5]]


In [80]:
x = np.arange(16)
b, y, z, a = np.split(x, [3, 7,10]) # [3, 7, 10] represent the break points
print(b, y, z, a)

[0 1 2] [3 4 5 6] [7 8 9] [10 11 12 13 14 15]


In [81]:
grid = x.reshape((4, 4))
print(grid)
u, v = np.vsplit(grid, [2])
w, x = np.hsplit(grid, [2])
print(u, v)
print(w, x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
